# @NPU_Api_HostAddress = https://localhost:5001
@NPU_Api_HostAddress = https://npuapp.azurewebsites.net

### Create a new NPU
POST {{NPU_Api_HostAddress}}/v1/api/npus?Name=TestNPU&Description=This%20is%20a%20test
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="Images"; filename="test-image.jpeg"
Content-Type: image/jpeg

< ./images/npu/test-image.jpeg
--boundary--

### Work on NPU with id:
@NPU_Id = 123456

### Get a specific NPU by ID
GET {{NPU_Api_HostAddress}}/v1/api/npus/{{NPU_Id}}

### Get NPUs with pagination
GET {{NPU_Api_HostAddress}}/v1/api/npus?page=1&pageSize=10&searchTerm=test&sortOrderKey=CreatedAt&ascending=true

### Post a score for an NPU
POST {{NPU_Api_HostAddress}}/v1/api/npus/{{NPU_Id}}/score
Content-Type: application/json

{
  "npuId": "{{NPU_Id}}",
  "creativity": 5,
  "uniqueness": 4
}
